name: "${project.name}"
version: "${project.version}"
api: ["1.0.13"]
main: com.mefrreex.formcreator.FormCreator

softdepend:
  - "PlaceholderAPI"

depend:
  - "FormConstructor"

permissions:
  formcreator:
    default: true
  formcreator.open:
    default: op
  formcreator.info:
    default: true