name: "${project.name}"
version: "${project.version}"
api: ["2.0.0"]
main: com.mefrreex.formcreator.FormCreator

softdepend:
  - "PlaceholderAPI"
  - "ChestCreator"

depend:
  - "FormConstructor"

permissions:
  formcreator:
    default: true
  formcreator.open:
    default: op
  formcreator.info:
    default: true